<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Portefeuille',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Programmes',
'page' => 'list' ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Projets',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'vue_repartition_projets',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Raci',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Activites',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Budgets',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Depenses',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'vue_suivi_budgetaire',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'vue_avancement_global',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'vue_performance_projets',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Indicateurs',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Valeurs_indicateurs',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Documents_projets',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Archivages',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'vue_projets_derive',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Tableau_De_Bord',
'page' => 'dashboard' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'grid' => array( 'welcome_item12',
'welcome_item13',
'welcome_item',
'welcome_item4',
'welcome_item14',
'welcome_item6',
'welcome_item8',
'welcome_item9',
'welcome_item5',
'welcome_item1',
'welcome_item2',
'welcome_item11',
'welcome_item15',
'welcome_item10',
'welcome_item7',
'welcome_item3',
'welcome_item16' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item' => 'grid',
'welcome_item4' => 'grid',
'welcome_item14' => 'grid',
'welcome_item6' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item5' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item11' => 'grid',
'welcome_item15' => 'grid',
'welcome_item10' => 'grid',
'welcome_item7' => 'grid',
'welcome_item3' => 'grid',
'welcome_item16' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item12',
'welcome_item13',
'welcome_item',
'welcome_item4',
'welcome_item14',
'welcome_item6',
'welcome_item8',
'welcome_item9',
'welcome_item5',
'welcome_item1',
'welcome_item2',
'welcome_item11',
'welcome_item15',
'welcome_item10',
'welcome_item7',
'welcome_item3',
'welcome_item16' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item12',
'welcome_item13',
'welcome_item',
'welcome_item4',
'welcome_item14',
'welcome_item6',
'welcome_item8',
'welcome_item9',
'welcome_item5',
'welcome_item1',
'welcome_item2',
'welcome_item11',
'welcome_item15',
'welcome_item10',
'welcome_item7',
'welcome_item3',
'welcome_item16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Portefeuille',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Portefeuille',
'type' => 6 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Programmes',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Programmes',
'type' => 6 ),
'background' => '#CD853F',
'linkType' => 0 ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Projets',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Projets',
'type' => 6 ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#CD853F',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vue_repartition_projets',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Repartition Projets' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Raci',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Matrice RACI' ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Activites',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Activites',
'type' => 6 ),
'background' => '#3CB371',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Budgets',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Budgets',
'type' => 6 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Depenses',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Depenses',
'type' => 6 ),
'background' => '#3CB371',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vue_suivi_budgetaire',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Suivi Budgetaire' ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vue_avancement_global',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Avancement Global' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vue_performance_projets',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Performance Projets' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Indicateurs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Indicateurs',
'type' => 6 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Valeurs_indicateurs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Valeurs_indicateurs',
'type' => 6 ),
'background' => '#778899',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Documents_projets',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Documents_projets',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Archivages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Archivages',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vue_projets_derive',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Projets Derive' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#6B8E23',
'linkType' => 0 ),
'logo' => array( 'type' => 'logo',
'logo' => array( 'table' => null,
'type' => 8 ) ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'expand_button' => array( 'type' => 'expand_button' ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Tableau_De_Bord',
'linkPage' => 'dashboard',
'linkText' => array( 'table' => 'Tableau_De_Bord',
'type' => 6 ),
'background' => '#DC143C',
'linkType' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>