<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'categorie',
'chef_projet_id',
'code_projet',
'date_debut',
'date_fin',
'description',
'direction_responsable',
'id',
'id_programme',
'localisation',
'niveau_maturite',
'nom',
'objectif',
'statut' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'categorie' => array( 'import_field' ),
'chef_projet_id' => array( 'import_field1' ),
'code_projet' => array( 'import_field2' ),
'date_debut' => array( 'import_field3' ),
'date_fin' => array( 'import_field4' ),
'description' => array( 'import_field5' ),
'direction_responsable' => array( 'import_field6' ),
'id' => array( 'import_field7' ),
'id_programme' => array( 'import_field8' ),
'localisation' => array( 'import_field9' ),
'niveau_maturite' => array( 'import_field10' ),
'nom' => array( 'import_field11' ),
'objectif' => array( 'import_field12' ),
'statut' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'categorie',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'chef_projet_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'code_projet',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'date_debut',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'date_fin',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'description',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'direction_responsable',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'id_programme',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'localisation',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'niveau_maturite',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'nom',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'objectif',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'statut',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>