<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item10',
'dashboard-item',
'dashboard-item5',
'dashboard-item3',
'dashboard-item1',
'dashboard-item4',
'dashboard-item2',
'dashboard-item8',
'dashboard-item6',
'dashboard-item7',
'dashboard-item9' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item10' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item5' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item8' => 'grid',
'dashboard-item6' => 'grid',
'dashboard-item7' => 'grid',
'dashboard-item9' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item5',
'dashboard-item6',
'dashboard-item7',
'dashboard-item8',
'dashboard-item9',
'dashboard-item10' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_ProjetsEnCours',
'dashType' => 0,
'dashName' => 'kpi_ProjetsEnCours_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets en cours' ),
'icon' => array( 'fa' => 'bell' ) ),
'elementName' => 'kpi_ProjetsEnCours_grid',
'table' => 'kpi_ProjetsEnCours',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_ActivitesEnCours',
'dashType' => 0,
'dashName' => 'kpi_ActivitesEnCours_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Activités en cours' ),
'icon' => array( 'glyph' => 'leaf' ) ),
'elementName' => 'kpi_ActivitesEnCours_grid',
'table' => 'kpi_ActivitesEnCours',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_projets_en_retard',
'dashType' => 0,
'dashName' => 'kpi_projets_en_retard_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets en retard' ),
'icon' => array( 'fa' => 'gift' ) ),
'elementName' => 'kpi_projets_en_retard_grid',
'table' => 'kpi_projets_en_retard',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_taux_execution_budgetaire',
'dashType' => 0,
'dashName' => 'kpi_taux_execution_budgetaire_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => '% exécut° budget' ),
'icon' => array( 'fa' => 'tag' ) ),
'elementName' => 'kpi_taux_execution_budgetaire_grid',
'table' => 'kpi_taux_execution_budgetaire',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_projets_termines',
'dashType' => 0,
'dashName' => 'kpi_projets_termines_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets terminés' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'kpi_projets_termines_grid',
'table' => 'kpi_projets_termines',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_activites_terminees',
'dashType' => 0,
'dashName' => 'kpi_activites_terminees_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'star' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Activités terminés' ) ),
'elementName' => 'kpi_activites_terminees_grid',
'table' => 'kpi_activites_terminees',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_activites_en_retard',
'dashType' => 0,
'dashName' => 'kpi_activites_en_retard_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'photo' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Activités en retard' ) ),
'elementName' => 'kpi_activites_en_retard_grid',
'table' => 'kpi_activites_en_retard',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_projets_depassement_budget',
'dashType' => 0,
'dashName' => 'kpi_projets_depassement_budget_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets hors budget' ) ),
'elementName' => 'kpi_projets_depassement_budget_grid',
'table' => 'kpi_projets_depassement_budget',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_BudgetGlobal',
'dashType' => 0,
'dashName' => 'kpi_BudgetGlobal_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'headphones' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Budget global' ) ),
'elementName' => 'kpi_BudgetGlobal_grid',
'table' => 'kpi_BudgetGlobal',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_depenses_realisees',
'dashType' => 0,
'dashName' => 'kpi_depenses_realisees_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Dépense réalisées' ) ),
'elementName' => 'kpi_depenses_realisees_grid',
'table' => 'kpi_depenses_realisees',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_budget_restant',
'dashType' => 0,
'dashName' => 'kpi_budget_restant_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'tag' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Budget restant' ) ),
'elementName' => 'kpi_budget_restant_grid',
'table' => 'kpi_budget_restant',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'kpi_ProjetsEnCours_projets_en_cours' => array( array( 'field' => 'projets_en_cours',
'table' => 'kpi_ProjetsEnCours' ) ),
'kpi_BudgetGlobal_budget_global' => array( array( 'field' => 'budget_global',
'table' => 'kpi_BudgetGlobal' ) ),
'kpi_projets_termines_activites_en_cours' => array( array( 'field' => 'activites_en_cours',
'table' => 'kpi_projets_termines' ) ),
'kpi_activites_terminees_projets_termines' => array( array( 'field' => 'projets_termines',
'table' => 'kpi_activites_terminees' ) ),
'kpi_projets_depassement_budget_projets_depassement_budget' => array( array( 'field' => 'projets_depassement_budget',
'table' => 'kpi_projets_depassement_budget' ) ),
'kpi_taux_execution_budgetaire_taux_execution_budgetaire' => array( array( 'field' => 'taux_execution_budgetaire',
'table' => 'kpi_taux_execution_budgetaire' ) ) ),
'allSearchFields' => array( 'kpi_ProjetsEnCours_projets_en_cours',
'kpi_BudgetGlobal_budget_global',
'kpi_projets_termines_activites_en_cours',
'kpi_activites_terminees_projets_termines',
'kpi_projets_depassement_budget_projets_depassement_budget',
'kpi_taux_execution_budgetaire_taux_execution_budgetaire' ),
'googleLikeFields' => array( 'kpi_ProjetsEnCours_projets_en_cours' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item10' ),
'customCSS' => '/* --- STYLE GLOBAL DU DASHBOARD --- */
.dashboard-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 15px;
  justify-content: center;
  margin-top: 10px;
}

/* --- STYLE DES CARTES KPI --- */
.dashboard-card {
  background: #ffffff;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  border-radius: 12px;
  width: 220px;
  padding: 20px;
  text-align: center;
  transition: transform 0.2s ease-in-out;
}

.dashboard-card:hover {
  transform: scale(1.05);
}

/* --- COULEURS DES STATUTS --- */
.kpi-encours {
  border-top: 6px solid #2e7d32;
}
.kpi-termine {
  border-top: 6px solid #1565c0;
}
.kpi-retard {
  border-top: 6px solid #ef6c00;
}
.kpi-budget {
  border-top: 6px solid #c62828;
}

/* --- TITRE & VALEUR --- */
.dashboard-card h4 {
  font-size: 15px;
  color: #555;
  margin-bottom: 8px;
}

.dashboard-card h2 {
  font-size: 28px;
  margin: 0;
  font-weight: bold;
}
',
'width' => '100px' ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ),
'width' => '100px',
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5' ),
'width' => '100px' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ),
'width' => '100px' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ),
'width' => '100px' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ),
'width' => '100px' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ),
'width' => '100px' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'dashboard-item8' ),
'width' => '100px' ),
'c8' => array( 'model' => 'c1',
'items' => array(  ),
'width' => '' ),
'c12' => array( 'model' => 'c1',
'items' => array( 'dashboard-item6' ),
'width' => '100px' ),
'c13' => array( 'model' => 'c1',
'items' => array( 'dashboard-item7' ),
'width' => '100px' ),
'c14' => array( 'model' => 'c1',
'items' => array( 'dashboard-item9' ),
'width' => '100px' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'kpi_ProjetsEnCours',
'dashType' => 0,
'dashName' => 'kpi_ProjetsEnCours_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets en cours' ),
'icon' => array( 'fa' => 'bell' ) ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'kpi_ActivitesEnCours',
'dashType' => 0,
'dashName' => 'kpi_ActivitesEnCours_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Activités en cours' ),
'icon' => array( 'glyph' => 'leaf' ) ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'kpi_BudgetGlobal',
'dashType' => 0,
'dashName' => 'kpi_BudgetGlobal_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'headphones' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Budget global' ) ),
'expand_button' => array( 'type' => 'expand_button' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'kpi_projets_termines',
'dashType' => 0,
'dashName' => 'kpi_projets_termines_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets terminés' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'kpi_activites_terminees',
'dashType' => 0,
'dashName' => 'kpi_activites_terminees_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'star' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Activités terminés' ) ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'kpi_projets_depassement_budget',
'dashType' => 0,
'dashName' => 'kpi_projets_depassement_budget_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets hors budget' ) ),
'dashboard-item6' => array( 'type' => 'dashboard-item',
'table' => 'kpi_projets_en_retard',
'dashType' => 0,
'dashName' => 'kpi_projets_en_retard_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Projets en retard' ),
'icon' => array( 'fa' => 'gift' ) ),
'dashboard-item7' => array( 'type' => 'dashboard-item',
'table' => 'kpi_activites_en_retard',
'dashType' => 0,
'dashName' => 'kpi_activites_en_retard_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'photo' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Activités en retard' ) ),
'dashboard-item8' => array( 'type' => 'dashboard-item',
'table' => 'kpi_depenses_realisees',
'dashType' => 0,
'dashName' => 'kpi_depenses_realisees_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'gift' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Dépense réalisées' ) ),
'dashboard-item9' => array( 'type' => 'dashboard-item',
'table' => 'kpi_budget_restant',
'dashType' => 0,
'dashName' => 'kpi_budget_restant_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'tag' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Budget restant' ) ),
'dashboard-item10' => array( 'type' => 'dashboard-item',
'table' => 'kpi_taux_execution_budgetaire',
'dashType' => 0,
'dashName' => 'kpi_taux_execution_budgetaire_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '130px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => '% exécut° budget' ),
'icon' => array( 'fa' => 'tag' ) ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>