<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'projets_en_cours',
'projets_termines',
'projets_en_retard',
'projets_depassement_budget',
'activites_en_cours',
'activites_en_retard',
'activites_terminees',
'budget_global',
'depenses_realisees',
'budget_restant',
'taux_execution_budgetaire' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'projets_en_cours' => array( 'import_field' ),
'projets_termines' => array( 'import_field1' ),
'projets_en_retard' => array( 'import_field2' ),
'projets_depassement_budget' => array( 'import_field3' ),
'activites_en_cours' => array( 'import_field4' ),
'activites_en_retard' => array( 'import_field5' ),
'activites_terminees' => array( 'import_field6' ),
'budget_global' => array( 'import_field7' ),
'depenses_realisees' => array( 'import_field8' ),
'budget_restant' => array( 'import_field9' ),
'taux_execution_budgetaire' => array( 'import_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'projets_en_cours',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'projets_termines',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'projets_en_retard',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'projets_depassement_budget',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'activites_en_cours',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'activites_en_retard',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'activites_terminees',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'budget_global',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'depenses_realisees',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'budget_restant',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'taux_execution_budgetaire',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>