<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tableau_de_bord  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_Tableau_De_Bord_snippet( &$header, &$icon )
	{
		function OnTableau_De_Bord_snippet($header, $icon)
{
    echo '
    <div class="dashboard-grid">
      <div class="dashboard-card kpi-encours">
        <h4>Projets en cours</h4>
        <h2>'.$data["projets_en_cours"].'</h2>
      </div>

      <div class="dashboard-card kpi-termine">
        <h4>Projets terminés</h4>
        <h2>'.$data["projets_termines"].'</h2>
      </div>

      <div class="dashboard-card kpi-retard">
        <h4>Projets en retard</h4>
        <h2>'.$data["projets_en_retard"].'</h2>
      </div>

      <div class="dashboard-card kpi-budget">
        <h4>Dépassement budget</h4>
        <h2>'.$data["projets_depassement_budget"].'</h2>
      </div>

      <div class="dashboard-card kpi-termine">
        <h4>Budget global</h4>
        <h2>'.$data["budget_global"].'</h2>
      </div>

      <div class="dashboard-card kpi-encours">
        <h4>Dépenses réalisées</h4>
        <h2>'.$data["depenses_realisees"].'</h2>
      </div>

      <div class="dashboard-card kpi-retard">
        <h4>Budget restant</h4>
        <h2>'.$data["budget_restant"].'</h2>
      </div>
    </div>';
}
;
	}
		// dashboatd snippets function
	function event_Tableau_De_Bord_snippet1( &$header, &$icon )
	{
		function OnTableau_De_Bord_snippet($header, $icon)
{
    echo '
    <div class="dashboard-grid">
      <div class="dashboard-card kpi-encours">
        <h4>Projets en cours</h4>
        <h2>'.$data["projets_en_cours"].'</h2>
      </div>

      <div class="dashboard-card kpi-termine">
        <h4>Projets terminés</h4>
        <h2>'.$data["projets_termines"].'</h2>
      </div>

      <div class="dashboard-card kpi-retard">
        <h4>Projets en retard</h4>
        <h2>'.$data["projets_en_retard"].'</h2>
      </div>

      <div class="dashboard-card kpi-budget">
        <h4>Dépassement budget</h4>
        <h2>'.$data["projets_depassement_budget"].'</h2>
      </div>

      <div class="dashboard-card kpi-termine">
        <h4>Budget global</h4>
        <h2>'.$data["budget_global"].'</h2>
      </div>

      <div class="dashboard-card kpi-encours">
        <h4>Dépenses réalisées</h4>
        <h2>'.$data["depenses_realisees"].'</h2>
      </div>

      <div class="dashboard-card kpi-retard">
        <h4>Budget restant</h4>
        <h2>'.$data["budget_restant"].'</h2>
      </div>
    </div>';
}
;
	}

}
?>
